# Helm chart values for production deployment of lco/simbad2k application

replicaCount: 3

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-public
  hosts:
    - simbad2k.lco.global

# CPU/memory resource requests/limits
resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 128Mi
