# Helm chart values for production deployment of lco/simbad2k application

replicaCount: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-ingress-private
  hosts:
    - simbad2k.lco.gtn

# CPU/memory resource requests/limits
resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    cpu: 500m
    memory: 128Mi
